### ISSUE TITLE
[4ª ITERAÇÃO] Implementar 3 refatorações - I

### ISSUE THREAD

**Issue by ynjisng** [2023-1-ES-UFAPE/gestao-monitoramento-frota#51]
Realizar que ajudem a melhorar a estrutura do código implementado nas iterações anteriores. 
Cada refatoração deve estar em um commit diferente. A mensagem do commit deve conter a palavra “Refactoring” e indicar a
refatoração e o tipo dela especificado no [catálogo](https://refactoring.com/catalog/). Por exemplo, “Refactoring – Extract Method”.

**Comment by RickyM7** [comment]
Três refatorações que caem no campo de "Rename Field" se não me engano seriam: renomear "Caminhaos" para "Caminhoes", "Rotum" para "Rotas" e "Albums" para "Albuns". Não irei fazer mas deixo a ideia aqui pra quem quiser.
